language: python

python:
  - 3.5

before_install:
  - export DJANGO_SETTINGS_MODULE=settings.base
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
