# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=15),
        ),
    ]
